[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
events_solana = "Bes8gPHw26kmAFXD3dcgZPtmKMmqody3Qzt73mZ8p5ez"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/merlin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
